# Generated by Django 3.0.5 on 2020-06-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', help_text='동영상 URL', max_length=1024),
            preserve_default=False,
        ),
    ]
